# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.cache/wt} [current_project]
set_property parent.project_path {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/sources_1/imports/new/Multiplexer_4way.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/sources_1/imports/new/Generic_counter.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/sources_1/imports/new/Decoding_the)world.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/new/ALU.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/new/Timer.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/new/ROM.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/new/RAM.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/new/Processor.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/new/MouseInterface.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/new/LEDInterface.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/new/7SegInterface.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/new/Wrapper.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/sources_1/new/MouseMasterSM.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/sources_1/new/MouseTransmitter.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/sources_1/new/MouseReceiver.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/sources_1/new/MouseTransceiver.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/new/IR_processor.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/new/IRTransmitterSM(1).v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/new/IR_Transmitter_Interface.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/new/BUTTON_COMMAND.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/new/Counter_10Hz.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/Downloads/VGA_Sig_Gen.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/Downloads/Frame_Buffer.v}
  {/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/sources_1/imports/new/VGA.v}
}
read_xdc {{/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/constrs_1/imports/new/assessment_constraints.xdc}}
set_property used_in_implementation false [get_files {{/home/s1786991/DSD/DSD4/IR and Mouse/IR and Mouse.srcs/constrs_1/imports/new/assessment_constraints.xdc}}]

synth_design -top Wrapper -part xc7a35ticpg236-1L -keep_equivalent_registers
write_checkpoint -noxdef Wrapper.dcp
catch { report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb }
