# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s1786991/DSD/DSD4/Microprocessor_VGA/Microprocessor_VGA.cache/wt [current_project]
set_property parent.project_path /home/s1786991/DSD/DSD4/Microprocessor_VGA/Microprocessor_VGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/s1786991/DSD/DSD4/Microprocessor_VGA/Microprocessor_VGA.srcs/sources_1/new/Generic_Counter.v
  /home/s1786991/DSD/DSD4/Microprocessor_VGA/Microprocessor_VGA.srcs/sources_1/new/VGA_Sig_Gen.v
  /home/s1786991/DSD/DSD4/Microprocessor_VGA/Microprocessor_VGA.srcs/sources_1/new/Frame_Buffer.v
  /home/s1786991/DSD/DSD4/Microprocessor_VGA/Microprocessor_VGA.srcs/sources_1/new/VGA.v
}
read_xdc /home/s1786991/DSD/DSD4/Microprocessor_VGA/Microprocessor_VGA.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/s1786991/DSD/DSD4/Microprocessor_VGA/Microprocessor_VGA.srcs/constrs_1/new/constraints.xdc]

synth_design -top VGA -part xc7a35tcpg236-1
write_checkpoint -noxdef VGA.dcp
catch { report_utilization -file VGA_utilization_synth.rpt -pb VGA_utilization_synth.pb }
