# COLOUR_IN to SLIDE SWITCHES[0:15]
set_property PACKAGE_PIN V17 [get_ports {CONFIG_COLOURS[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[0]}]
set_property PACKAGE_PIN V16 [get_ports {CONFIG_COLOURS[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[1]}]
set_property PACKAGE_PIN W16 [get_ports {CONFIG_COLOURS[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[2]}]
set_property PACKAGE_PIN W17 [get_ports {CONFIG_COLOURS[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[3]}]
set_property PACKAGE_PIN W15 [get_ports {CONFIG_COLOURS[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[4]}]
set_property PACKAGE_PIN V15 [get_ports {CONFIG_COLOURS[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[5]}]
set_property PACKAGE_PIN W14 [get_ports {CONFIG_COLOURS[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[6]}]
set_property PACKAGE_PIN W13 [get_ports {CONFIG_COLOURS[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[7]}]
set_property PACKAGE_PIN V2 [get_ports {CONFIG_COLOURS[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[8]}]
set_property PACKAGE_PIN T3 [get_ports {CONFIG_COLOURS[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[9]}]
set_property PACKAGE_PIN T2 [get_ports {CONFIG_COLOURS[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[10]}]
set_property PACKAGE_PIN R3 [get_ports {CONFIG_COLOURS[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[11]}]
set_property PACKAGE_PIN W2 [get_ports {CONFIG_COLOURS[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[12]}]
set_property PACKAGE_PIN U1 [get_ports {CONFIG_COLOURS[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[13]}]
set_property PACKAGE_PIN T1 [get_ports {CONFIG_COLOURS[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[14]}]   
set_property PACKAGE_PIN R2 [get_ports {CONFIG_COLOURS[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CONFIG_COLOURS[15]}]   

# COLOUR_OUT to VGA COLOUR
set_property PACKAGE_PIN G19 [get_ports {COLOUR_OUT[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[0]}]
set_property PACKAGE_PIN H19 [get_ports {COLOUR_OUT[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[1]}]
set_property PACKAGE_PIN J19 [get_ports {COLOUR_OUT[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[2]}]
set_property PACKAGE_PIN N19 [get_ports {COLOUR_OUT[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[3]}]
set_property PACKAGE_PIN J17 [get_ports {COLOUR_OUT[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[4]}]
set_property PACKAGE_PIN H17 [get_ports {COLOUR_OUT[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[5]}]
set_property PACKAGE_PIN G17 [get_ports {COLOUR_OUT[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[6]}]
set_property PACKAGE_PIN D17 [get_ports {COLOUR_OUT[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[7]}]
set_property PACKAGE_PIN N18 [get_ports {COLOUR_OUT[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[8]}]
set_property PACKAGE_PIN L18 [get_ports {COLOUR_OUT[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[9]}]
set_property PACKAGE_PIN K18 [get_ports {COLOUR_OUT[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[10]}]
set_property PACKAGE_PIN J18 [get_ports {COLOUR_OUT[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[11]}]
   
# RESET
set_property PACKAGE_PIN U18 [get_ports RESET]
    set_property IOSTANDARD LVCMOS33 [get_ports RESET]

# ENABLE    
set_property PACKAGE_PIN T17 [get_ports FRAMEBUFFER_ENABLE]
    set_property IOSTANDARD LVCMOS33 [get_ports FRAMEBUFFER_ENABLE]
set_property PACKAGE_PIN W19 [get_ports GENERATOR_ENABLE]
        set_property IOSTANDARD LVCMOS33 [get_ports GENERATOR_ENABLE]

# HS, VS
set_property PACKAGE_PIN P19 [get_ports VGA_HS]
    set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property PACKAGE_PIN R19 [get_ports VGA_VS]
    set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]




# CLK   
set_property PACKAGE_PIN W5 [get_ports CLK]
    set_property IOSTANDARD LVCMOS33 [get_ports CLK]